/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import * as vscode from 'vscode';
import { randomBytes } from 'crypto';
import { URL } from 'url';
import { ContainerType, ContainerTypeAppPermission, ContainerTypeRegistration } from '../../models/schemas';
import { ext } from '../../utils/extensionVariables';
import { AuthenticationState } from '../../services/AuthenticationState';
import { serializeError, StorageExplorerApi } from '../../services/StorageExplorer/StorageExplorerApi';
import { diagnoseAccessDenied } from '../../services/StorageExplorer/accessDenied';
import { checkExtensionAppPermissions, ensureExtensionAppPermissions, readGrantedExtensionAppScopes } from '../../utils/ExtensionAppPermissions';
import { missingCapabilitiesForOperation, satisfiesExtensionAppBaseline } from '../../utils/ExtensionAppPermissionScopes';
import { DevelopmentTreeViewProvider } from '../treeview/development/DevelopmentTreeViewProvider';
import { createGraphClient } from '../../services/StorageExplorer/graphClient';
import { evaluateExternalUrl } from '../../services/StorageExplorer/externalUrlPolicy';
import { escapeHtmlAttribute, sanitizeCspSource, serializeJsonForHtml } from '../../services/StorageExplorer/htmlEncoding';
import { SerializedError, StorageExplorerPanelState, StorageExplorerReadiness } from '../../services/StorageExplorer/protocol';

/**
 * Generate a CSP script nonce.
 *
 * Uses a CSPRNG: the nonce is what stops injected markup from executing, so a
 * predictable value (as `Math.random()` would give) would let an attacker who can
 * influence the page guess it and author a `<script nonce=...>` the CSP accepts.
 * 128 bits of entropy, base64url-encoded to stay safe inside the CSP header.
 */
function getNonce(): string {
    return randomBytes(16).toString('base64')
        .replace(/\+/g, '-')
        .replace(/\//g, '_')
        .replace(/=+$/, '');
}

/** Shape of a message arriving from the webview. Every field is untrusted. */
interface IncomingMessage {
    command?: unknown;
    har?: unknown;
    url?: unknown;
    requestId?: unknown;
    op?: unknown;
    params?: unknown;
}

/** Commands the host is willing to act on. Anything else is dropped. */
const KNOWN_COMMANDS = ['rpc/request', 'exportHar', 'openExternal', 'grantPermissions'];

/** Upper bound on an exported HAR. Large captures are legitimate; unbounded ones are not. */
const MAX_HAR_LENGTH = 32 * 1024 * 1024;

/** Correlation ids are generated by `api/rpc.ts` and are short. */
const MAX_REQUEST_ID_LENGTH = 128;

/**
 * Render an untrusted value for the output channel.
 *
 * Webview-supplied strings must never be written verbatim: newlines would let a
 * compromised webview forge log lines, and unbounded values would flood the channel.
 */
function forLog(value: unknown, maxLength = 64): string {
    if (typeof value !== 'string') { return `<${typeof value}>`; }
    const oneLine = value.replace(/[\r\n\t]/g, ' ');
    return oneLine.length > maxLength ? `${oneLine.slice(0, maxLength)}…` : oneLine;
}

/**
 * Manages one Storage Explorer WebviewPanel per ContainerTypeRegistration.
 * Opening the same registration twice reveals the existing panel.
 *
 * The webview is treated as semi-trusted: it never receives a Microsoft Graph
 * bearer token. It requests named operations over `rpc/request` and this class
 * executes them against Graph in the extension host, returning only the results.
 */
export class StorageExplorerPanel {
    private static readonly _panels = new Map<string, StorageExplorerPanel>();

    private readonly _panel: vscode.WebviewPanel;
    private readonly _registrationId: string;
    private readonly _containerTypeId: string;
    private readonly _readiness: StorageExplorerReadiness;
    private readonly _api: StorageExplorerApi;
    private readonly _disposables: vscode.Disposable[] = [];
    private _isDisposed = false;
    /** In-flight permission prompt, so a burst of failed calls raises a single dialog. */
    private _permissionPrompt: Promise<void> | undefined;
    /** Last grant logged, so the per-operation read reports changes instead of every call. */
    private _lastLoggedScopes: string | undefined;
    /**
     * Whether the grant satisfied the tree's all-or-nothing baseline the last time the panel
     * reconciled the two.
     *
     * Seeded from the readiness the panel opened with, and only for the two readiness states
     * the grant decides. `billingBlocked` and `unregistered` are settled by something other
     * than permissions, so a grant change tells us nothing about whether those rows are
     * stale — reconciling them would refresh the tree for no reason. `undefined` therefore
     * means "not ours to reconcile".
     */
    private _grantMatchedTree: boolean | undefined;

    private constructor(
        panel: vscode.WebviewPanel,
        registrationId: string,
        state: StorageExplorerPanelState
    ) {
        this._panel = panel;
        this._registrationId = registrationId;
        this._containerTypeId = state.containerTypeId;
        this._readiness = state.readiness;
        this._grantMatchedTree = state.readiness === 'ready' ? true
            : state.readiness === 'missingPermissions' ? false
                : undefined;

        // Bound to this panel's container type: container-type-scoped operations use
        // this value rather than anything supplied by the webview. The Graph client —
        // and therefore the bearer token — stays in the extension host.
        const client = createGraphClient(request => {
            this._post({ command: 'networkLog', request });
        });
        this._api = new StorageExplorerApi(
            state.containerTypeId,
            client,
            // Capability gating reads the live grant on the extension host; the webview never
            // learns anything about it beyond the scope names a denied call names.
            () => this._readGrantedScopesForGating()
        );

        this._panel.webview.html = StorageExplorerPanel._buildHtml(this._panel.webview, state);
        this._panel.onDidDispose(() => this._dispose(), null, this._disposables);

        this._panel.webview.onDidReceiveMessage(
            (message: IncomingMessage) => this._handleMessage(message),
            null,
            this._disposables
        );
    }

    private async _handleMessage(message: IncomingMessage): Promise<void> {
        if (!message || typeof message !== 'object') {
            ext.outputChannel.warn('[StorageExplorerPanel] dropped non-object message');
            return;
        }

        const command = typeof message.command === 'string' ? message.command : '';
        if (KNOWN_COMMANDS.indexOf(command) === -1) {
            ext.outputChannel.warn(
                `[StorageExplorerPanel] dropped message with unrecognized command: ${forLog(message.command)}`
            );
            return;
        }
        ext.outputChannel.debug(`[StorageExplorerPanel] received message: command=${command}`);

        switch (command) {
            case 'rpc/request':
                await this._handleRpcRequest(message);
                return;
            case 'exportHar':
                if (typeof message.har !== 'string' || !message.har) {
                    ext.outputChannel.warn('[StorageExplorerPanel] exportHar without a string payload — dropped');
                    return;
                }
                if (message.har.length > MAX_HAR_LENGTH) {
                    ext.outputChannel.warn('[StorageExplorerPanel] exportHar payload too large — dropped');
                    return;
                }
                await StorageExplorerPanel._handleExportHar(message.har);
                return;
            case 'openExternal':
                await StorageExplorerPanel._handleOpenExternal(message.url);
                return;
            case 'grantPermissions':
                // Raised by the user clicking "Grant permissions" on a failed listing. Routes
                // through the same prompt a denied call raises, so both paths behave alike.
                await this._promptForPermissions();
                return;
        }
    }

    /**
     * Open a webview-supplied URL in the OS, but only if it passes the allow-list.
     *
     * `openExternal` leaves the webview sandbox and is not subject to the panel CSP, so an
     * unvalidated URL here is both an exfiltration channel and — for schemes such as
     * `file:`, `vscode:` or `command:` — a local-action primitive.
     */
    private static async _handleOpenExternal(rawUrl: unknown): Promise<void> {
        const decision = evaluateExternalUrl(rawUrl);
        if (!decision.allowed) {
            ext.outputChannel.warn(
                `[StorageExplorerPanel] blocked openExternal (${decision.description}): ${decision.reason}`
            );
            void vscode.window.showWarningMessage(
                vscode.l10n.t('Blocked an attempt to open an unexpected external link ({0}).', decision.description)
            );
            return;
        }

        // Only the scheme and host are logged: SPO download and preview URLs carry
        // pre-authenticated tokens in their query string.
        ext.outputChannel.info(`[StorageExplorerPanel] opening external URL: ${decision.description}`);
        try {
            const uri = vscode.Uri.parse(decision.url, true);
            // Guard against a parser differential: if VS Code's URI parser reads a
            // different authority than the one that was validated, do not proceed.
            if (uri.scheme === 'https' && uri.authority.toLowerCase() !== new URL(decision.url).hostname) {
                ext.outputChannel.warn('[StorageExplorerPanel] blocked openExternal: URI authority mismatch');
                return;
            }
            await vscode.env.openExternal(uri);
            ext.outputChannel.info('[StorageExplorerPanel] openExternal succeeded');
        } catch (error) {
            ext.outputChannel.error(`[StorageExplorerPanel] openExternal failed: ${error}`);
        }
    }

    /**
     * Run one webview-requested Graph operation and post its result back.
     * Unknown operations and malformed parameters are rejected by `StorageExplorerApi`.
     */
    private async _handleRpcRequest(message: IncomingMessage): Promise<void> {
        const requestId = typeof message.requestId === 'string'
            && message.requestId.length > 0
            && message.requestId.length <= MAX_REQUEST_ID_LENGTH
            ? message.requestId
            : undefined;
        if (!requestId) {
            ext.outputChannel.warn('[StorageExplorerPanel] rpc/request without a usable requestId — dropped');
            return;
        }

        try {
            const result = await this._api.execute(message.op, message.params, {
                onProgress: data => this._post({ command: 'rpc/progress', requestId, data }),
            });
            this._post({ command: 'rpc/response', requestId, ok: true, result });
        } catch (error) {
            const original = serializeError(error);
            // Log the raw failure, not the diagnosis — when the diagnosis is wrong, this is
            // the only place the underlying Graph message and code survive.
            ext.outputChannel.error(
                `[StorageExplorerPanel._handleRpcRequest] ${forLog(message.op)} failed: `
                + `${original.message}${original.code ? ` (code=${forLog(original.code, 40)})` : ''}`
                + `${original.statusCode ? ` [HTTP ${original.statusCode}]` : ''}`
            );
            this._post({ command: 'rpc/response', requestId, ok: false, error: await this._diagnose(original) });
        }
    }

    /**
     * Diagnose a failure before it reaches the webview.
     *
     * A missing extension-app permission grant is tagged so the webview can render a
     * "permissions required" state instead of an empty folder, and the user is prompted
     * to grant; on success the webview is told to reload.
     */
    private async _diagnose(serialized: SerializedError): Promise<SerializedError> {
        if (!this._containerTypeId) {
            return serialized;
        }

        const { error, missingPermissions } = await diagnoseAccessDenied(
            serialized,
            // Strict form: a failed lookup must throw rather than read as "not granted",
            // otherwise an unrelated Graph outage would be reported as a permissions problem.
            () => checkExtensionAppPermissions(this._containerTypeId)
        );
        if (missingPermissions) {
            void this._promptForPermissions();
        }
        return error;
    }

    /**
     * Prompt for the missing grant and report the outcome to the webview.
     *
     * Single-flight: a burst of failed calls, or a click landing while the automatic prompt
     * is still open, must not stack dialogs. Every caller shares the one prompt and the one
     * result message.
     */
    private _promptForPermissions(): Promise<void> {
        if (!this._permissionPrompt) {
            this._permissionPrompt = (async () => {
                const granted = await ensureExtensionAppPermissions(this._containerTypeId);
                // The grant changed under us; drop the memoized capability set so the next
                // call re-reads it instead of denying with a stale answer.
                if (granted) { this._api.invalidateGrantedScopes(); }
                this._post({ command: 'permissionsGrantResult', granted });
            })()
                .catch(error => {
                    ext.outputChannel.warn(
                        `[StorageExplorerPanel] extension app permission prompt failed: ${error?.message ?? error}`
                    );
                    // The webview is waiting on this; leaving it out hangs the button.
                    this._post({ command: 'permissionsGrantResult', granted: false });
                })
                .finally(() => { this._permissionPrompt = undefined; });
        }
        return this._permissionPrompt;
    }

    /**
     * Read the extension app's live grant for capability gating, reporting what it saw.
     *
     * Every authorization decision in this panel rests on this one value, so when the UI
     * disagrees with what an operator believes they granted, the grant the host actually
     * read is the first thing that has to be checkable. Only scope *names* are written —
     * never the token, the app id, or the tenant — and only when the set changes, so the
     * per-operation read does not flood the channel.
     */
    private async _readGrantedScopesForGating(): Promise<readonly ContainerTypeAppPermission[]> {
        try {
            const granted = await readGrantedExtensionAppScopes(this._containerTypeId);
            const fingerprint = [...granted].sort().join(',');
            if (fingerprint !== this._lastLoggedScopes) {
                this._lastLoggedScopes = fingerprint;
                ext.outputChannel.info(
                    '[StorageExplorerPanel] extension app delegated scopes on this container type: '
                    + (granted.length ? [...granted].sort().join(', ') : '(none)')
                );
            }
            this._reconcileTreeRow(granted);
            return granted;
        } catch (error) {
            // Fails closed in `StorageExplorerApi`, but a silent denial is indistinguishable
            // from an empty grant, so say which one this was.
            this._lastLoggedScopes = undefined;
            ext.outputChannel.error(
                '[StorageExplorerPanel] could not read the extension app grant; every gated '
                + `operation will be denied until this succeeds: ${(error as Error)?.message ?? error}`
            );
            throw error;
        }
    }

    /**
     * Correct the Development tree when this panel's live grant read disagrees with the
     * readiness the tree row is displaying.
     *
     * The tree reads the grant once, when `ContainerTypesTreeItem` builds its children, and
     * caches the result; nothing invalidates that cache when the grant is changed out of band
     * (an admin edit, another tool, a direct Graph call). This panel reads the grant live on
     * every gated operation, so it is the first place in the extension to learn the truth —
     * and leaving the two surfaces contradicting each other is worse than a redundant refresh.
     *
     * Fires only on a transition, so a steady state costs nothing no matter how many
     * operations the panel runs.
     */
    private _reconcileTreeRow(granted: readonly ContainerTypeAppPermission[]): void {
        if (this._grantMatchedTree === undefined) { return; }

        const satisfiesBaseline = satisfiesExtensionAppBaseline(granted);
        if (satisfiesBaseline === this._grantMatchedTree) { return; }

        this._grantMatchedTree = satisfiesBaseline;
        ext.outputChannel.info(
            '[StorageExplorerPanel] the extension app grant no longer matches the Development '
            + `tree (baseline ${satisfiesBaseline ? 'now satisfied' : 'no longer satisfied'}); `
            + 'refreshing the tree'
        );

        try {
            DevelopmentTreeViewProvider.getInstance().refresh();
        } catch (error) {
            // A tree that could not be refreshed is stale, not broken: the panel itself is
            // still gated correctly, so this must never take down the operation that ran.
            ext.outputChannel.warn(
                '[StorageExplorerPanel] could not refresh the Development tree: '
                + `${(error as Error)?.message ?? error}`
            );
        }
    }

    /** Post to the webview unless the panel has already been torn down. */
    private _post(message: unknown): void {
        if (this._isDisposed) {
            return;
        }
        void this._panel.webview.postMessage(message);
    }

    // ------------------------------------------------------------------
    // Public API
    // ------------------------------------------------------------------

    public static async open(
        containerType: ContainerType,
        registration: ContainerTypeRegistration | null,
        readiness: StorageExplorerReadiness = 'ready'
    ): Promise<void> {
        // Blocked container types have no registration to key on, so the container type id
        // keys the panel instead. Either way one panel exists per container type.
        const registrationId = registration?.id ?? `ct:${containerType.id}`;
        const unregisteredKey = `ct:${containerType.id}`;
        // A panel opened before registration is keyed on the container type, so look under
        // that key too: otherwise finishing setup would leave a stale blocked panel open
        // alongside the ready one.
        const existing = StorageExplorerPanel._panels.get(registrationId)
            ?? (registrationId === unregisteredKey
                ? undefined
                : StorageExplorerPanel._panels.get(unregisteredKey));
        if (existing) {
            if (existing._registrationId === registrationId && existing._readiness === readiness) {
                existing._panel.reveal();
                return;
            }
            // The onboarding surface it is showing no longer describes this container type
            // (registration or the extension-app grant has since landed), and the surface is
            // baked into the webview state at creation time. Replace it with a fresh panel.
            existing._dispose();
        }

        const panel = vscode.window.createWebviewPanel(
            'speStorageExplorer',
            `${containerType.name} – Storage Explorer`,
            vscode.ViewColumn.One,
            {
                enableScripts: true,
                retainContextWhenHidden: true,
                localResourceRoots: [
                    vscode.Uri.joinPath(ext.context.extensionUri, 'out', 'webviewApp'),
                    vscode.Uri.joinPath(ext.context.extensionUri, 'media')
                ]
            }
        );
        panel.iconPath = vscode.Uri.joinPath(ext.context.extensionUri, 'media', 'sharepoint-embedded-icon.png');

        // No token is pre-fetched or embedded: the webview asks the host to perform
        // Graph calls instead of performing them itself.
        const state: StorageExplorerPanelState = {
            appName: containerType.name,
            tenantDomain: AuthenticationState.getCurrentAccountSync()?.domain ?? 'local tenant',
            containerTypeId: containerType.id,
            registrationId: registration?.id ?? '',
            readiness,
            // Scope names only, so the onboarding surface can name the grant it is waiting on.
            requiredScopes: readiness === 'missingPermissions'
                ? missingCapabilitiesForOperation('containers.list', []) as string[]
                : undefined,
        };

        const instance = new StorageExplorerPanel(panel, registrationId, state);
        StorageExplorerPanel._panels.set(registrationId, instance);
    }

    /** Reveal the panel for a registration if one is already open. */
    public static reveal(registrationId: string): boolean {
        const existing = StorageExplorerPanel._panels.get(registrationId);
        if (!existing) { return false; }
        existing._panel.reveal();
        return true;
    }

    /**
     * Close every Storage Explorer panel bound to a container type.
     *
     * There should normally be only one, but panels can be keyed by either a registration
     * or the container type while setup is incomplete. Matching the bound container type
     * ensures an old panel cannot survive registration changes or container-type deletion.
     *
     * @returns The number of panels closed.
     */
    public static closeForContainerType(containerTypeId: string): number {
        const matchingPanels = [...new Set(StorageExplorerPanel._panels.values())]
            .filter(panel => panel._containerTypeId === containerTypeId);
        for (const panel of matchingPanels) {
            panel._dispose();
        }
        return matchingPanels.length;
    }

    // ------------------------------------------------------------------
    // Private helpers
    // ------------------------------------------------------------------

    private static async _handleExportHar(har: string): Promise<void> {
        const tmpDir = require('os').tmpdir();
        const path = require('path');
        const fs = require('fs');
        const fileName = `storage-explorer-${Date.now()}.har`;
        const filePath = path.join(tmpDir, fileName);
        fs.writeFileSync(filePath, har, 'utf8');
        const doc = await vscode.workspace.openTextDocument(vscode.Uri.file(filePath));
        await vscode.window.showTextDocument(doc, { preview: false });
    }

    private static _buildHtml(webview: vscode.Webview, state: StorageExplorerPanelState): string {
        const base = ext.context.extensionUri;
        const asUri = (path: string[]) =>
            webview.asWebviewUri(vscode.Uri.joinPath(base, ...path)).toString();

        const scriptUri = escapeHtmlAttribute(asUri(['out', 'webviewApp', 'assets', 'index.js']));
        const styleUri  = escapeHtmlAttribute(asUri(['out', 'webviewApp', 'assets', 'style.css']));
        const nonce = escapeHtmlAttribute(getNonce());
        const cspSource = sanitizeCspSource(webview.cspSource);

        // `graph.microsoft.com` is intentionally absent: all Graph traffic now originates
        // from the extension host. The webview only talks directly to pre-authenticated
        // *.sharepoint.com upload-session URLs, which carry no Authorization header.
        //
        // `base-uri` and `form-action` are not covered by `default-src`, so both are denied
        // explicitly: the first stops an injected `<base>` from re-pointing relative URLs, the
        // second stops an injected `<form>` from posting panel content to an arbitrary host.
        // `style-src` still needs `unsafe-inline` because the component library injects styles
        // at runtime; scripts remain nonce-gated with no `unsafe-inline` fallback.
        //
        // The policy is emitted verbatim rather than HTML-escaped — it is built from literals
        // plus a sanitized `cspSource`, so it cannot break out of the attribute, and this avoids
        // making script gating depend on entity decoding of its `'single quotes'`.
        const csp = [
            `default-src 'none'`,
            `connect-src https://*.sharepoint.com`,
            `font-src ${cspSource}`,
            `img-src ${cspSource} data:`,
            `style-src ${cspSource} 'unsafe-inline'`,
            `script-src 'nonce-${nonce}'`,
            `object-src 'none'`,
            `base-uri 'none'`,
            `form-action 'none'`,
        ].join('; ');

        // Panel state is tenant- and app-controlled (`appName` is the container type display
        // name), so it is never interpolated into executable script. It is emitted as inert
        // `application/json` — which the HTML parser treats as raw text and never executes — and
        // escaped so it cannot close the element and break out into markup. The nonce-gated
        // bootstrap below lifts it onto `window` for the bundle, which loads later in the body.
        const stateJson = serializeJsonForHtml(state);

        return /* html */`<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="Content-Security-Policy" content="${csp}">
  <link rel="stylesheet" href="${styleUri}">
  <title>Storage Explorer</title>
  <script type="application/json" id="spe-state">${stateJson}</script>
  <script nonce="${nonce}">
    (function () {
      var el = document.getElementById('spe-state');
      try {
        window.__STORAGE_EXPLORER_STATE__ = el ? JSON.parse(el.textContent) : undefined;
      } catch (e) {
        window.__STORAGE_EXPLORER_STATE__ = undefined;
        console.error('[StorageExplorer] Failed to parse panel state.', e);
      }
    })();
  </script>
</head>
<body>
  <div id="root"></div>
  <script nonce="${nonce}" src="${scriptUri}"></script>
</body>
</html>`;
    }

    private _dispose(): void {
        if (this._isDisposed) {
            return;
        }
        this._isDisposed = true;
        if (StorageExplorerPanel._panels.get(this._registrationId) === this) {
            StorageExplorerPanel._panels.delete(this._registrationId);
        }
        this._panel.dispose();
        for (const d of this._disposables) {
            d.dispose();
        }
        this._disposables.length = 0;
    }
}
